from os import environ


VariantDir("build", "src", duplicate=0)

FLAGS = [
    "-std=c++1y",
    "-O3",
    "-pipe"
]

ENV = Environment(
    ENV=environ,
    CXX="g++",
    CPPFLAGS=['-Wno-unused-value'],
    CXXFLAGS=FLAGS,
    LINKFLAGS=FLAGS,
    CPPPATH=["#include"],
)

SRC = Glob("build/**.cpp")
ENV.SharedLibrary("_snes_env.so", SRC)